### ISSUE TITLE
Why Not Use Canvas?

### ISSUE THREAD

**Issue by noahbuscher** [DesignerNews/pixel-picker#1]
Is there any reason in particular you are using `div` elements for pixels instead of drawing pixels to a canvas, then figuring out the mouse coordinates for when the user clicks?

**Comment by jodyheavener** [comment]
No reason - in fact, you're right, canvas would be better (and less taxing on the DOM) - this was just a rewrite of the previous version. We'll get there one day!

**Comment by noahbuscher** [comment]
Pull request coming your way soon. :wink:

**Comment by noahbuscher** [comment]
Coming together!

![](http://noah.li/1g8Hu+)

**Comment by noahbuscher** [comment]
Okay! I finished the pull request!

Also, here's a demo of left + right clicks (green circle around cursor = right click):

![](http://noah.li/198By+)

**Comment by jodyheavener** [comment]
Closing in favor of continuing conversation on #2
